### ISSUE TITLE
Can't join MUC

### ISSUE THREAD

**Issue by lloydwatkin** [xmpp-ftw/xmpp-ftw-muc#50]
From https://github.com/xmpp-ftw/xmpp-ftw-buddycloud/issues/30 via @robotnic:

I try this

```
3:::{"type":0,"data":["xmpp.muc.join",{"room":"seehaus@channels.buddycloud.com","nick":"aaa"}],"id":5}
```

no answer from server.

**Comment by lloydwatkin** [comment]
I am able to join a MUC with no problems, please see screenshot. Could you test via https://xmpp-ftw.jit.su/demo, and test via a standard client?

![screenshot from 2015-01-18 23 21 59](https://cloud.githubusercontent.com/assets/271622/5794512/ee1f9b18-9f68-11e4-908b-eee87c466724.png)

**Comment by robotnic** [comment]
It works if I'm using
new Primus("https://xmpp-ftw.jit.su/");
but it's not working if I'm using
new Primus("https://laos.buddycloud.com");

Also my local version of xmpp-ftw does not work.

**Comment by lloydwatkin** [comment]
Then this is a deployment issue and is something @abmargb will need to look
at :)
