### ISSUE TITLE
Login with password

### ISSUE THREAD

**Issue by robotnic** [xmpp-ftw/xmpp-ftw-muc#51]
I'm missing the password at
https://xmpp-ftw.jit.su/manual/multi-user-chat/#join-a-room

Should look like:
{"type":0,"data":["xmpp.muc.join",{"room":"testing@channels.buddycloud.com","nick":"eluag","password":"1234"}],"id":6}

**Comment by lloydwatkin** [comment]
Thanks, just pushed a new version of the plugin and will update the documentation now.
